// <auto-generated />
using System;
using FaturaOtica.Infrastructure.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaturaOtica.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaturaOtica.Domain.Identity.IdentityAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_usuario_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_auditoria_tenant_id");

                    b.HasIndex("TenantId", "ActorUserId")
                        .HasDatabaseName("ix_auditoria_tenant_id_autor_usuario_id");

                    b.HasIndex("TenantId", "BranchId")
                        .HasDatabaseName("ix_auditoria_tenant_id_filial_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_auditoria_tenant_id_ocorrido_em");

                    b.HasIndex("TenantId", "TargetUserId")
                        .HasDatabaseName("ix_auditoria_tenant_id_alvo_usuario_id");

                    b.ToTable("auditoria", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_auditoria_acao", "acao IN ('GrantAccess', 'RevokeAccess', 'BlockUser')");

                            t.HasCheckConstraint("ck_auditoria_alvo_usuario_id_nao_vazio", "alvo_usuario_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_auditoria_autor_usuario_id_nao_vazio", "autor_usuario_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_auditoria_escopo", "(acao = 'BlockUser' AND papel IS NULL AND filial_id IS NULL) OR\n(acao IN ('GrantAccess', 'RevokeAccess') AND papel IS NOT NULL AND\n    ((papel IN ('Owner', 'AccessAdministrator') AND filial_id IS NULL) OR\n     (papel IN ('Seller', 'BranchManager') AND filial_id IS NOT NULL)))");

                            t.HasCheckConstraint("ck_auditoria_filial_id_nao_vazio", "filial_id IS NULL OR filial_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_auditoria_id_nao_vazio", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_auditoria_metadados_imutaveis", "criado_por IS NULL AND atualizado_em IS NULL AND atualizado_por IS NULL");

                            t.HasCheckConstraint("ck_auditoria_papel", "papel IS NULL OR papel IN ('Owner', 'AccessAdministrator', 'Seller', 'BranchManager')");

                            t.HasCheckConstraint("ck_auditoria_tenant_id_nao_vazio", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.HasKey("Id")
                        .HasName("pk_filiais");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_filiais_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_filiais_tenant_id");

                    b.ToTable("filiais", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_filiais_id_nao_vazio", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_filiais_tenant_id_nao_vazio", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityBranchGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_concessoes_filiais");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_concessoes_filiais_tenant_id");

                    b.HasIndex("TenantId", "BranchId")
                        .HasDatabaseName("ix_concessoes_filiais_tenant_id_filial_id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_concessoes_filiais_tenant_id_usuario_id");

                    b.HasIndex("TenantId", "UserId", "BranchId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_concessoes_filiais_tenant_id_usuario_id_filial_id_papel");

                    b.ToTable("concessoes_filiais", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_concessoes_filiais_filial_id_nao_vazio", "filial_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_concessoes_filiais_id_nao_vazio", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_concessoes_filiais_papel", "papel IN ('Seller', 'BranchManager')");

                            t.HasCheckConstraint("ck_concessoes_filiais_tenant_id_nao_vazio", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_concessoes_filiais_usuario_id_nao_vazio", "usuario_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_tenants_id_nao_vazio", "id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityTenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_papeis_usuarios");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_papeis_usuarios_tenant_id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_papeis_usuarios_tenant_id_usuario_id");

                    b.HasIndex("TenantId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_papeis_usuarios_tenant_id_usuario_id_papel");

                    b.ToTable("papeis_usuarios", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_papeis_usuarios_id_nao_vazio", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_papeis_usuarios_papel", "papel IN ('Owner', 'AccessAdministrator')");

                            t.HasCheckConstraint("ck_papeis_usuarios_tenant_id_nao_vazio", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_papeis_usuarios_usuario_id_nao_vazio", "usuario_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_normalizado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ux_usuarios_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_usuarios_tenant_id");

                    b.HasIndex("TenantId", "EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_tenant_id_email_normalizado");

                    b.ToTable("usuarios", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_email_normalizado", "length(email_normalizado) > 0 AND email_normalizado = lower(btrim(email_normalizado))");

                            t.HasCheckConstraint("ck_usuarios_id_nao_vazio", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_usuarios_senha_hash", "senha_hash IS NULL OR length(btrim(senha_hash)) > 0");

                            t.HasCheckConstraint("ck_usuarios_status", "status IN ('Pending', 'Active', 'Blocked')");

                            t.HasCheckConstraint("ck_usuarios_tenant_id_nao_vazio", "tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FaturaOtica.Domain.Identity.IdentityAuditEvent", b =>
                {
                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_tenants");

                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_usuarios_autor");

                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityBranch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_auditoria_filiais");

                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TargetUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_usuarios_alvo");
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityBranch", b =>
                {
                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_filiais_tenants");
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityBranchGrant", b =>
                {
                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_concessoes_filiais_tenants");

                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityBranch", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "BranchId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_concessoes_filiais_filiais");

                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_concessoes_filiais_usuarios");
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityTenantRole", b =>
                {
                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_papeis_usuarios_tenants");

                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_papeis_usuarios_usuarios");
                });

            modelBuilder.Entity("FaturaOtica.Infrastructure.Identity.IdentityUser", b =>
                {
                    b.HasOne("FaturaOtica.Infrastructure.Identity.IdentityTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
